name: ✏️ 更新地点信息
description: 更新已有地点的信息（地址、营业时间等）
title: "[更新] "
labels: ["update"]
body:
  - type: markdown
    attributes:
      value: |
        发现信息有误或过时？帮助我们更新！
        
  - type: input
    id: place-name
    attributes:
      label: 地点名称
      description: 需要更新的地点
      placeholder: 例如：南五咖啡
    validations:
      required: true
      
  - type: textarea
    id: what-to-update
    attributes:
      label: 需要更新的内容
      description: 详细说明哪些信息需要更新
      placeholder: |
        例如：
        - 营业时间改为 09:00-20:00
        - 人均消费涨到 55 元
        - 地址变更为...
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: 补充说明
      description: 其他需要说明的信息

